package app.controller;

import app.model.Greeting;
import app.model.Teste;
import app.repository.TesteRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

@RestController
public class GreetingController {
    private static final String template = "Helllllllladjawllo, %s!";
    private final AtomicLong counter = new AtomicLong();
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TesteRepository userRepository;

    @RequestMapping(value = "/greeting", method = {RequestMethod.GET, RequestMethod.POST})
    public Greeting greeting(
            @RequestParam(value = "name", defaultValue = "World") String name) {
        return new Greeting(counter.incrementAndGet(),
                String.format(template, name));
    }

    @RequestMapping(value = "/teste", method = {RequestMethod.GET, RequestMethod.POST})
    public Optional<Teste> teste() {
        return userRepository.findById(4);
    }
}
